# Generated by Django 5.0 on 2024-01-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halalweb', '0002_eatery_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatery',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
